services:
  # Backend API Service
  - type: web
    name: logiservice-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/users
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: logiservice-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend Web Service
  - type: web
    name: logiservice-frontend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build && npm install -g serve
    startCommand: cd frontend && serve -s build -l 10000
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: logiservice-backend
          property: host

databases:
  # MongoDB Database
  - name: logiservice-db
    databaseName: logiservice
    user: logiservice_user
    region: frankfurt
    plan: free
